### ISSUE TITLE
Console: Error while fetching devices

### ISSUE THREAD

**Issue by zone11** [open-network-infrastructure/ttn-ch-status#7]
The Backend reports an error while fetching the devices of an application in the console:

`Could not list devices: Internal error: connection error: desc = "transport: authentication handshake failed: read tcp 172.20.0.2:60738->10.0.210.100:1904: read: connection reset by peer"`

This occurs in the application overview and the device list of an application.

**Comment by gonzalocasas** [comment]
Console lost connection, restarted `console_console_1` container.
